sudo: required
services:
    - docker

before_install:
    - docker build -t harshalbadade50/docker-multi-container -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true harshalbadade50/docker-multi-container npm run test

after_success:
    - docker build -t harshalbadade50/multi-client ./client
    - docker build -t harshalbadade50/multi-nginx ./nginx
    - docker build -t harshalbadade50/multi-server ./server
    - docker build -t harshalbadade50/multi-worker ./worker
    # Login to the Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # Take those image and push them to Docker Hub
    - docker push harshalbadade50/multi-client:latest
    - docker push harshalbadade50/multi-nginx:latest
    - docker push harshalbadade50/multi-server:latest
    - docker push harshalbadade50/multi-worker:latest